name: Bug Report
description: 用于报告问题
title: "[Bug]: "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        感谢您提交问题报告！请提供以下信息以帮助我们更好地理解和解决您的问题。

  - type: textarea
    id: description
    attributes:
      label: 问题描述以及复现步骤
      description: 请清晰简明地描述遇到的问题。
      placeholder: 问题描述...

  - type: textarea
    id: additional_context
    attributes:
      label: 其他上下文
      description: 在此添加关于问题的任何其他上下文。
      placeholder: 其他上下文...
