name: Sync Image
description: 同步单个镜像
labels:
- porter
body:
- type: markdown
  attributes:
    value: |
      # ↑↑↑ 填入你要同步的镜像
      ## 请包含 域名/路径:标签

- type: checkboxes
  attributes:
    label: 检查清单
    options:
    - label: 确保镜像格式正确 (域名/路径:标签)
- type: markdown
  attributes:
    value: |
      ### 域名示例
      - docker.io/
      - registry.k8s.io/

      ### 标签示例
      - :latest
      - :v1

      ### 完整镜像示例
      - docker.io/library/busybox:latest
      - docker.io/kindest/node:v1.30.0
      - registry.k8s.io/kubectl:v1.30.0
